#!/bin/bash

# Read SSID and password from ~/.wificnt/wifi.md file
ssid=$(grep -oP '(?<=SSID = ").*(?=")' ~/.wificnt/wifi.md)
password=$(grep -oP '(?<=PASSWORD = ").*(?=")' ~/.wificnt/wifi.md)

# Connect to Wi-Fi network
nmcli device wifi connect "$ssid" password "$password"
